language: node_js
node_js:
  - "10"
before_install:
  - git config --global user.email "dejan@fajfar.com"
  - git config --global user.name "travisbuild"
deploy:
  provider: npm
  email: "dejan@fajfar.com"
  api_key: "$npm_key"
  on: 
    branch: release
